# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3164ea5714a661192f8bdc3ccb6495777f9831557c1263d3d09e6f57da608ce17245278f5ea311c1e74b4379b09db793d642409da95eedf581dbd00a0a6092f3

test:
  secret_key_base: a0b795bc0aaca58cd72299f5a32b1c7373b63396919d85cdaa319c3d1795236f105253acfc59df013d4cf0ee4076deb3c5435708051007be34e8c70d71a66ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
